services:
  web:
    build: .
    command: >
      sh -c "echo '
      ----------------------------------------
       App running at http://localhost:8000
      ----------------------------------------'
      && uv run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - /app/.venv
    env_file:
      - .env
    ports:
      - "8000:8000"
