# Generated by Django 5.2.13 on 2026-04-16 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'item type',
                'verbose_name_plural': 'item types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('level', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='encyclopedia.itemtype')),
            ],
            options={
                'verbose_name': 'equipment',
                'verbose_name_plural': 'equipment',
                'ordering': ['level', 'name'],
            },
        ),
    ]
