# Generated by Django 5.2.13 on 2026-04-21 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0003_alter_equipment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='ap_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='conditions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='critical_hit_bonus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='critical_hit_probability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='image_hd_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='image_hq_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_weapon',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='max_cast_per_turn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='parent_set_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='parent_set_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='equipment',
            name='pods',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='range_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='range_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='recipe',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.CreateModel(
            name='EquipmentEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_type_id', models.IntegerField()),
                ('effect_type_name', models.CharField(max_length=255)),
                ('effect_type_is_active', models.BooleanField(default=False)),
                ('effect_type_is_meta', models.BooleanField(default=False)),
                ('int_minimum', models.IntegerField(default=0)),
                ('int_maximum', models.IntegerField(default=0)),
                ('ignore_int_min', models.BooleanField(default=False)),
                ('ignore_int_max', models.BooleanField(default=False)),
                ('formatted', models.CharField(blank=True, max_length=512)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='encyclopedia.equipment')),
            ],
            options={
                'verbose_name': 'equipment effect',
                'verbose_name_plural': 'equipment effects',
            },
        ),
    ]
