# Generated by Django 5.2.13 on 2026-04-22 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("encyclopedia", "0004_equipment_ap_cost_equipment_conditions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Set",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ankama_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("level", models.IntegerField(default=0)),
                ("items_count", models.IntegerField(default=0)),
                ("equipment_ids", models.JSONField(default=list)),
                ("contains_cosmetics", models.BooleanField(default=False)),
                ("contains_cosmetics_only", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "set",
                "verbose_name_plural": "sets",
                "ordering": ["level", "name"],
            },
        ),
        migrations.CreateModel(
            name="SetEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pieces_count", models.IntegerField()),
                ("effect_type_id", models.IntegerField()),
                ("effect_type_name", models.CharField(max_length=255)),
                ("effect_type_is_active", models.BooleanField(default=False)),
                ("effect_type_is_meta", models.BooleanField(default=False)),
                ("int_minimum", models.IntegerField(default=0)),
                ("int_maximum", models.IntegerField(default=0)),
                ("ignore_int_min", models.BooleanField(default=False)),
                ("ignore_int_max", models.BooleanField(default=False)),
                ("formatted", models.CharField(blank=True, max_length=512)),
                (
                    "set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="effects",
                        to="encyclopedia.set",
                    ),
                ),
            ],
            options={
                "verbose_name": "set effect",
                "verbose_name_plural": "set effects",
                "ordering": ["pieces_count"],
            },
        ),
    ]
