# Generated by Django 5.2.13 on 2026-04-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0005_set_seteffect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
